# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_clientform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DigitizationClient(object):
    def setupUi(self, DigitizationClient):
        DigitizationClient.setObjectName("DigitizationClient")
        DigitizationClient.resize(683, 441)
        self.centralwidget = QtWidgets.QWidget(DigitizationClient)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonStartSession = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStartSession.setObjectName("buttonStartSession")
        self.gridLayout.addWidget(self.buttonStartSession, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.labelImageCount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelImageCount.setFont(font)
        self.labelImageCount.setObjectName("labelImageCount")
        self.horizontalLayout_2.addWidget(self.labelImageCount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.labelRate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelRate.setFont(font)
        self.labelRate.setObjectName("labelRate")
        self.horizontalLayout_2.addWidget(self.labelRate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.labelElapsedTime = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelElapsedTime.setFont(font)
        self.labelElapsedTime.setObjectName("labelElapsedTime")
        self.horizontalLayout_2.addWidget(self.labelElapsedTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 4, 1, 1)
        self.sessionPathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sessionPathLineEdit.setReadOnly(False)
        self.sessionPathLineEdit.setObjectName("sessionPathLineEdit")
        self.gridLayout.addWidget(self.sessionPathLineEdit, 0, 4, 1, 1)
        self.buttonSessionPath = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSessionPath.setObjectName("buttonSessionPath")
        self.gridLayout.addWidget(self.buttonSessionPath, 0, 0, 1, 1)
        self.sessionStatusLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sessionStatusLineEdit.setReadOnly(True)
        self.sessionStatusLineEdit.setObjectName("sessionStatusLineEdit")
        self.gridLayout.addWidget(self.sessionStatusLineEdit, 4, 4, 1, 1)
        self.sessionDataTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.sessionDataTextBrowser.setEnabled(True)
        self.sessionDataTextBrowser.setMaximumSize(QtCore.QSize(16777215, 146))
        self.sessionDataTextBrowser.setObjectName("sessionDataTextBrowser")
        self.gridLayout.addWidget(self.sessionDataTextBrowser, 3, 4, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 7, 0, 1, 5)
        self.buttonSessionData = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSessionData.setObjectName("buttonSessionData")
        self.gridLayout.addWidget(self.buttonSessionData, 3, 0, 1, 1)
        self.buttonEndSession = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEndSession.setObjectName("buttonEndSession")
        self.gridLayout.addWidget(self.buttonEndSession, 6, 0, 1, 1)
        DigitizationClient.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DigitizationClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 22))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        DigitizationClient.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DigitizationClient)
        self.statusbar.setObjectName("statusbar")
        DigitizationClient.setStatusBar(self.statusbar)
        self.actionStart_Session = QtWidgets.QAction(DigitizationClient)
        self.actionStart_Session.setObjectName("actionStart_Session")
        self.menuTest.addAction(self.actionStart_Session)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(DigitizationClient)
        QtCore.QMetaObject.connectSlotsByName(DigitizationClient)

    def retranslateUi(self, DigitizationClient):
        _translate = QtCore.QCoreApplication.translate
        DigitizationClient.setWindowTitle(_translate("DigitizationClient", "Digitization Client"))
        self.buttonStartSession.setText(_translate("DigitizationClient", "Start Session"))
        self.label.setText(_translate("DigitizationClient", "Images:"))
        self.labelImageCount.setText(_translate("DigitizationClient", "0"))
        self.label_3.setText(_translate("DigitizationClient", "Images/min.:"))
        self.labelRate.setText(_translate("DigitizationClient", "0"))
        self.label_2.setText(_translate("DigitizationClient", "Elapsed time:"))
        self.labelElapsedTime.setText(_translate("DigitizationClient", "0"))
        self.sessionPathLineEdit.setPlaceholderText(_translate("DigitizationClient", "full folder path"))
        self.buttonSessionPath.setText(_translate("DigitizationClient", "Set Session Path"))
        self.sessionStatusLineEdit.setPlaceholderText(_translate("DigitizationClient", "session status"))
        self.buttonSessionData.setText(_translate("DigitizationClient", "Set Session Data"))
        self.buttonEndSession.setText(_translate("DigitizationClient", "End Session"))
        self.menuTest.setTitle(_translate("DigitizationClient", "Menu"))
        self.actionStart_Session.setText(_translate("DigitizationClient", "Start Session"))

